INSERT INTO hangman_topics.word (word_name, topic_id) VALUES
('Armadillo', 1),
('Cheetah', 1),
('Chimpanzee', 1),
('Crocodile', 1),
('Dolphin', 1),
('Elephant', 1),
('Giraffe', 1),
('Gorilla', 1),
('Kangaroo', 1),
('Koala', 1),
('Lion', 1),
('Octopus', 1),
('Panda', 1),
('Penguin', 1),
('Peacock', 1),
('Platypus', 1),
('Polar Bear', 1),
('Rhinoceros', 1),
('Tiger', 1),
('Zebra', 1),
('Argentina', 2),
('Australia', 2),
('Brazil', 2),
('Canada', 2),
('China', 2),
('Egypt', 2),
('France', 2),
('Germany', 2),
('India', 2),
('Italy', 2),
('Japan', 2),
('Mexico', 2),
('Netherlands', 2),
('Nigeria', 2),
('Russia', 2),
('South Korea', 2),
('Spain', 2),
('Sweden', 2),
('United Kingdom', 2),
('United States', 2),
('Water', 3),
('Coffee', 3),
('Tea', 3),
('Orange Juice', 3),
('Lemonade', 3),
('Soda', 3),
('Milk', 3),
('Hot Chocolate', 3),
('Iced Tea', 3),
('Smoothie', 3),
('Cola', 3),
('Apple Juice', 3),
('Cranberry Juice', 3),
('Coconut Water', 3),
('Iced Coffee', 3),
('Grape Juice', 3),
('Almond Milk', 3),
('Fruit Punch', 3),
('Green Tea', 3),
('Sports Drink', 3),
('Burger', 4),
('Butter Chicken', 4),
('Chicken Curry', 4),
('Fried Rice', 4),
('Lasagna', 4),
('Meatball', 4),
('Omelette', 4),
('Pancakes', 4),
('Pasta Carbonara', 4),
('Pizza', 4),
('Roast Beef', 4),
('Spaghetti Bolognese', 4),
('Sushi', 4),
('Tandoori Chicken', 4),
('Tacos', 4),
('Tempura', 4),
('Teriyaki Salmon', 4),
('Tikka Masala', 4),
('Tortilla Soup', 4),
('Wonton Soup', 4),
('Apple', 5),
('Banana', 5),
('Blueberry', 5),
('Cherry', 5),
('Grape', 5),
('Kiwi', 5),
('Lemon', 5),
('Mango', 5),
('Orange', 5),
('Papaya', 5),
('Peach', 5),
('Pear', 5),
('Pineapple', 5),
('Plum', 5),
('Raspberry', 5),
('Strawberry', 5),
('Tangerine', 5),
('Watermelon', 5),
('Avocado', 5),
('Apricot', 5),
('Asparagus', 6),
('Beetroot', 6),
('Broccoli', 6),
('Brussels Sprouts', 6),
('Carrot', 6),
('Cauliflower', 6),
('Cucumber', 6),
('Eggplant', 6),
('Green Bean', 6),
('Kale', 6),
('Lettuce', 6),
('Mushroom', 6),
('Onion', 6),
('Pea', 6),
('Potato', 6),
('Radish', 6),
('Spinach', 6),
('Sweet Potato', 6),
('Tomato', 6),
('Zucchini', 6);